version: '2'
services:
  web:
    container_name: spinn3r_data_extract
    image: cortext/cortext_pytheas
    ports:
     - '5000:8080'
    volumes:
     - '.:/opt/spinn3r_data_extract'
     - './conf:/opt/spinn3r_data_extract/conf'
    restart: always 